// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgYUuwc41uQRcAKz0D9Q6M7LL9OhjncI',
    appId: '1:328632219739:web:f1dc422eb4289e8cc9277e',
    messagingSenderId: '328632219739',
    projectId: 'instagram-clone-e302f',
    authDomain: 'instagram-clone-e302f.firebaseapp.com',
    storageBucket: 'instagram-clone-e302f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeBq-eqZYUvSuGG8DzpelwL4kdfGF4Cak',
    appId: '1:328632219739:android:3939f5620d055cb6c9277e',
    messagingSenderId: '328632219739',
    projectId: 'instagram-clone-e302f',
    storageBucket: 'instagram-clone-e302f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjSpkoUR1LsPAQfJVaBnzRPj4VyqjWv6c',
    appId: '1:328632219739:ios:dad506016c5fa441c9277e',
    messagingSenderId: '328632219739',
    projectId: 'instagram-clone-e302f',
    storageBucket: 'instagram-clone-e302f.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjSpkoUR1LsPAQfJVaBnzRPj4VyqjWv6c',
    appId: '1:328632219739:ios:04304e40a0576a41c9277e',
    messagingSenderId: '328632219739',
    projectId: 'instagram-clone-e302f',
    storageBucket: 'instagram-clone-e302f.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
